// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANAYwLXfihQFvmuekIHmyQpluBZfQgn8k',
    appId: '1:396313071393:web:b01215d1e767fbda8ff860',
    messagingSenderId: '396313071393',
    projectId: 'dashboard-c3879',
    authDomain: 'dashboard-c3879.firebaseapp.com',
    storageBucket: 'dashboard-c3879.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuj87TTx9IUDtIgjUkm2dGdQkB_Y_UcQc',
    appId: '1:396313071393:android:b8b5f08e97f190368ff860',
    messagingSenderId: '396313071393',
    projectId: 'dashboard-c3879',
    storageBucket: 'dashboard-c3879.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2v60kvpwRt9lhMERcqQskXk4gfNrnfe4',
    appId: '1:396313071393:ios:893020415b514be18ff860',
    messagingSenderId: '396313071393',
    projectId: 'dashboard-c3879',
    storageBucket: 'dashboard-c3879.firebasestorage.app',
    iosBundleId: 'com.example.dashboardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2v60kvpwRt9lhMERcqQskXk4gfNrnfe4',
    appId: '1:396313071393:ios:893020415b514be18ff860',
    messagingSenderId: '396313071393',
    projectId: 'dashboard-c3879',
    storageBucket: 'dashboard-c3879.firebasestorage.app',
    iosBundleId: 'com.example.dashboardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANAYwLXfihQFvmuekIHmyQpluBZfQgn8k',
    appId: '1:396313071393:web:b01215d1e767fbda8ff860',
    messagingSenderId: '396313071393',
    projectId: 'dashboard-c3879',
    authDomain: 'dashboard-c3879.firebaseapp.com',
    storageBucket: 'dashboard-c3879.firebasestorage.app',
  );

}